# Generated by Django 4.0.10 on 2024-09-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=50)),
                ('tasks', models.ManyToManyField(to='task.taskmodel')),
            ],
        ),
    ]
