# Generated by Django 4.0.10 on 2024-09-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catmodel',
            name='tasks',
        ),
    ]
