# Generated by Django 4.0.10 on 2024-08-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_image',
            field=models.ImageField(default='media/meals/default.jpg', upload_to='meals/images'),
        ),
    ]
