# Generated by Django 4.0.10 on 2024-08-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fsat_name', models.CharField(max_length=60)),
                ('Last_name', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField(max_length=30)),
                ('Instrument_type', models.CharField(max_length=30)),
            ],
        ),
    ]
