# Generated by Django 4.0.10 on 2024-11-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musi',
            name='Instrument_type',
            field=models.CharField(max_length=100),
        ),
    ]
