# Generated by Django 5.0.7 on 2024-08-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.TextField(default='rIYADS'),
        ),
    ]
