# Generated by Django 4.0.10 on 2024-12-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_rename_ammount_transaction_amount_and_more'),
        ('accounts', '0003_useraddress_userbankaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userbankaccount'),
        ),
    ]
