# Generated by Django 4.0.10 on 2024-09-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0002_remove_catmodel_tasks'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='catagory_name',
            field=models.ManyToManyField(to='catagory.catmodel'),
        ),
    ]
