# Generated by Django 4.0.10 on 2024-12-01 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraddress_userbankaccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transaction', '0004_alter_transaction_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCreationmodel',
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
    ]
