# Generated by Django 5.0.7 on 2024-08-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('father_name', models.TextField()),
                ('address', models.TextField(default='Tetulia')),
            ],
        ),
    ]
