# Generated by Django 5.0.7 on 2024-08-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='addres',
            field=models.TextField(default='Ryaan'),
        ),
    ]
