# Generated by Django 4.0.10 on 2024-11-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('Musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musician.musi')),
            ],
        ),
    ]
